#!/bin/bash

# Copyright (C) 2020-2022 Pirx Developers - https://pirx.dev/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

first=0
echo -n '{"data":['
cat /etc/zabbix/scripts/ssl_cert_check.list 2>/dev/null | grep -E -v "(^#|^\s*$)" 2>/dev/null | while read ssl_host ssl_port ssl_domain ssl_timeout; do
  if [ "${first}" -eq 0 ]; then
    first=1
  else
    echo -n ','
  fi
  if [ -z "${ssl_domain}" ]; then
    ssl_domain="${ssl_host}"
  fi
  if [ -z "${ssl_timeout}" ]; then
    ssl_timeout="10"
  fi
  echo -n '{'
  echo -n '"{#HOST}":"'${ssl_host}'",'
  echo -n '"{#PORT}":"'${ssl_port}'",'
  echo -n '"{#DOMAIN}":"'${ssl_domain}'",'
  echo -n '"{#TIMEOUT}":"'${ssl_timeout}'"'
  echo -n '}'
done
echo -n ']}'
