#!/bin/bash

# Copyright (C) 2020-2022 Pirx Developers - https://pirx.dev/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if test -z "${1}"; then
  echo "Usage: ${0} <items|state|sync> [<item>]"
  exit 1
fi

if [ "${1}" = "items" ]; then
  echo -n '{"data":['
  cnt=0
  for md in $(ls -1d /sys/block/md[0-9]* 2>/dev/null | xargs -n 1 basename 2>/dev/null); do
    if [ "${cnt}" -ne  0 ]; then
      echo -n ','
    fi
    let cnt=cnt+1
    echo -n '{"{#DEVICE}":"'${md}'"}'
  done
  echo ']}'
  exit 0
elif [ "${1}" = "state" ]; then
  state=$(cat /sys/block/${2}/md/degraded 2>/dev/null)
  if [ "${state}" = "0" ]; then
    echo "1"
  else
    echo "0"
  fi
elif [ "${1}" = "sync" ]; then
  sync=$(cat /sys/block/${2}/md/sync_action 2>/dev/null)
  if [ "${sync}" = "idle" ]; then
    echo "1"
  else
    echo "0"
  fi
fi
